/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.ibm.jp.awag.common.validator.StringFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * クーポン更新API(CouponUpdate).IncentiveのInput DTOクラス。
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CouponUpdateInputDTOIncentive extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** クーポン本文テキスト(couponText) */
	@StringFormat(type = StringFormat.Type.FULL_CHAR, maxLength = 300)
	@JsonProperty("_couponText")
	private String couponText;

	/** 割引率(amount) */
	@StringFormat(type = StringFormat.Type.HALF_NUM, maxLength = 100)
	@JsonProperty("_amount")
	private String amount;

	/** 割引単位(unit) */
	@StringFormat(type = StringFormat.Type.HALF_NUM_CHAR, minLength = 1, maxLength = 99)
	@JsonProperty("_unit")
	private String unit;

	/** 対象商品(products) */
	@StringFormat(type = StringFormat.Type.HALF_CHAR, maxLength = 150)
	@JsonProperty("_products")
	private String products;

	/**
	 * クーポン本文テキスト(couponText)を取得する。
	 * 
	 * @return クーポン本文テキスト(couponText)
	 */
	public String getCouponText() {
		return couponText;
	}

	/**
	 * クーポン本文テキスト(couponText)を設定する。
	 * 
	 * @param couponText クーポン本文テキスト(couponText)
	 */
	public void setCouponText(String couponText) {
		this.couponText = couponText;
	}

	/**
	 * 割引率(amount)を取得する。
	 * 
	 * @return 割引率(amount)
	 */
	public String getAmount() {
		return amount;
	}

	/**
	 * 割引率(amount)を設定する。
	 * 
	 * @param amount 割引率(amount)
	 */
	public void setAmount(String amount) {
		this.amount = amount;
	}

	/**
	 * 割引単位(unit)を取得する。
	 * 
	 * @return 割引単位(unit)
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * 割引単位(unit)を設定する。
	 * 
	 * @param unit 割引単位(unit)
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * 対象商品(products)を取得する。
	 * 
	 * @return 対象商品(products)
	 */
	public String getProducts() {
		return products;
	}

	/**
	 * 対象商品(products)を設定する。
	 * 
	 * @param products 対象商品(products)
	 */
	public void setProducts(String products) {
		this.products = products;
	}

}