/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import java.util.List;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;
import com.ibm.jp.awag.common.validator.Required;
import com.ibm.jp.awag.common.validator.StringFormat;

/**
 * クーポン更新API(CouponUpdate)のInput DTOクラス。
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CouponUpdateInputDTO extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** (uuid) */
	@Required
	@StringFormat(type = StringFormat.Type.HALF_CHAR)
	private String uuid;

	/** クーポン利用可能店舗ID(providers) */
	@JsonProperty("providers")
	private List<String> providers;

	/** クーポン名(name) */
	@StringFormat(type = StringFormat.Type.FULL_CHAR, minLength = 1, maxLength = 30)
	@JsonProperty("name")
	private String name;

	/** クーポン説明(shortDescription) */
	@StringFormat(type = StringFormat.Type.FULL_CHAR, minLength = 1, maxLength = 100)
	@JsonProperty("short_description")
	private String shortDescription;

	/** クーポン利用条件(description) */
	@StringFormat(type = StringFormat.Type.FULL_CHAR, minLength = 1, maxLength = 1000)
	@JsonProperty("description")
	private String description;

	/** 表示順ポイント(priority) */
	@StringFormat(type = StringFormat.Type.HALF_NUM, minLength = 1, maxLength = 9999)
	@JsonProperty("priority")
	private String priority;

	/** 一人当たり利用可能枚数(userUsableCount) */
	@StringFormat(type = StringFormat.Type.HALF_NUM, minLength = 1, maxLength = 100)
	@JsonProperty("user_usable_count")
	private String userUsableCount;

	/** 全体利用上限枚数(totalUsableCount) */
	@StringFormat(type = StringFormat.Type.HALF_NUM)
	@JsonProperty("total_usable_count")
	private String totalUsableCount;

	/** 限定CP一人当たり配布枚数(userDistributableCount) */
	@StringFormat(type = StringFormat.Type.HALF_NUM, minLength = 1, maxLength = 100)
	@JsonProperty("user_distributable_count")
	private String userDistributableCount;

	/** 限定CP全体上限配布枚数(totalDistributableCount) */
	@StringFormat(type = StringFormat.Type.HALF_NUM)
	@JsonProperty("total_distributable_count")
	private String totalDistributableCount;

	/** 表示開始日時(visibleStartAt) */
	@StringFormat(type = StringFormat.Type.HALF_CHAR, minLength = 19, maxLength = 19)
	@JsonProperty("visible_start_at")
	private String visibleStartAt;

	/** 表示終了日時(visibleEndAt) */
	@StringFormat(type = StringFormat.Type.HALF_CHAR, minLength = 19, maxLength = 19)
	@JsonProperty("visible_end_at")
	private String visibleEndAt;

	/** 有効開始日時(usableStartAt) */
	@StringFormat(type = StringFormat.Type.HALF_CHAR, minLength = 19, maxLength = 19)
	@JsonProperty("usable_start_at")
	private String usableStartAt;

	/** 有効終了日時(usableEndAt) */
	@StringFormat(type = StringFormat.Type.HALF_CHAR, minLength = 19, maxLength = 19)
	@JsonProperty("usable_end_at")
	private String usableEndAt;

	/** 限定配布後有効日数(usableDays) */
	@StringFormat(type = StringFormat.Type.HALF_NUM, maxLength = 365)
	@JsonProperty("usable_days")
	private String usableDays;

	/** 公開ステータス(isOpen) */
	@JsonProperty("is_open")
	private String isOpen;

	/** 任意追加項目(AdditionalItems) */
	@Valid
	@JsonProperty("additional_items")
	private CouponUpdateInputDTOAdditionalItems additionalItems;

	/**
	 * (uuid)を取得する。
	 * 
	 * @return (uuid)
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * (uuid)を設定する。
	 * 
	 * @param uuid (uuid)
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * クーポン利用可能店舗ID(providers)を取得する。
	 * 
	 * @return クーポン利用可能店舗ID(providers)
	 */
	public List<String> getProviders() {
		return providers;
	}

	/**
	 * クーポン利用可能店舗ID(providers)を設定する。
	 * 
	 * @param providers クーポン利用可能店舗ID(providers)
	 */
	public void setProviders(List<String> providers) {
		this.providers = providers;
	}

	/**
	 * クーポン名(name)を取得する。
	 * 
	 * @return クーポン名(name)
	 */
	public String getName() {
		return name;
	}

	/**
	 * クーポン名(name)を設定する。
	 * 
	 * @param name クーポン名(name)
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * クーポン説明(shortDescription)を取得する。
	 * 
	 * @return クーポン説明(shortDescription)
	 */
	public String getShortDescription() {
		return shortDescription;
	}

	/**
	 * クーポン説明(shortDescription)を設定する。
	 * 
	 * @param shortDescription クーポン説明(shortDescription)
	 */
	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	/**
	 * クーポン利用条件(description)を取得する。
	 * 
	 * @return クーポン利用条件(description)
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * クーポン利用条件(description)を設定する。
	 * 
	 * @param description クーポン利用条件(description)
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * 表示順ポイント(priority)を取得する。
	 * 
	 * @return 表示順ポイント(priority)
	 */
	public String getPriority() {
		return priority;
	}

	/**
	 * 表示順ポイント(priority)を設定する。
	 * 
	 * @param priority 表示順ポイント(priority)
	 */
	public void setPriority(String priority) {
		this.priority = priority;
	}

	/**
	 * 一人当たり利用可能枚数(userUsableCount)を取得する。
	 * 
	 * @return 一人当たり利用可能枚数(userUsableCount)
	 */
	public String getUserUsableCount() {
		return userUsableCount;
	}

	/**
	 * 一人当たり利用可能枚数(userUsableCount)を設定する。
	 * 
	 * @param userUsableCount 一人当たり利用可能枚数(userUsableCount)
	 */
	public void setUserUsableCount(String userUsableCount) {
		this.userUsableCount = userUsableCount;
	}

	/**
	 * 全体利用上限枚数(totalUsableCount)を取得する。
	 * 
	 * @return 全体利用上限枚数(totalUsableCount)
	 */
	public String getTotalUsableCount() {
		return totalUsableCount;
	}

	/**
	 * 全体利用上限枚数(totalUsableCount)を設定する。
	 * 
	 * @param totalUsableCount 全体利用上限枚数(totalUsableCount)
	 */
	public void setTotalUsableCount(String totalUsableCount) {
		this.totalUsableCount = totalUsableCount;
	}

	/**
	 * 限定CP一人当たり配布枚数(userDistributableCount)を取得する。
	 * 
	 * @return 限定CP一人当たり配布枚数(userDistributableCount)
	 */
	public String getUserDistributableCount() {
		return userDistributableCount;
	}

	/**
	 * 限定CP一人当たり配布枚数(userDistributableCount)を設定する。
	 * 
	 * @param userDistributableCount 限定CP一人当たり配布枚数(userDistributableCount)
	 */
	public void setUserDistributableCount(String userDistributableCount) {
		this.userDistributableCount = userDistributableCount;
	}

	/**
	 * 限定CP全体上限配布枚数(totalDistributableCount)を取得する。
	 * 
	 * @return 限定CP全体上限配布枚数(totalDistributableCount)
	 */
	public String getTotalDistributableCount() {
		return totalDistributableCount;
	}

	/**
	 * 限定CP全体上限配布枚数(totalDistributableCount)を設定する。
	 * 
	 * @param totalDistributableCount 限定CP全体上限配布枚数(totalDistributableCount)
	 */
	public void setTotalDistributableCount(String totalDistributableCount) {
		this.totalDistributableCount = totalDistributableCount;
	}

	/**
	 * 表示開始日時(visibleStartAt)を取得する。
	 * 
	 * @return 表示開始日時(visibleStartAt)
	 */
	public String getVisibleStartAt() {
		return visibleStartAt;
	}

	/**
	 * 表示開始日時(visibleStartAt)を設定する。
	 * 
	 * @param visibleStartAt 表示開始日時(visibleStartAt)
	 */
	public void setVisibleStartAt(String visibleStartAt) {
		this.visibleStartAt = visibleStartAt;
	}

	/**
	 * 表示終了日時(visibleEndAt)を取得する。
	 * 
	 * @return 表示終了日時(visibleEndAt)
	 */
	public String getVisibleEndAt() {
		return visibleEndAt;
	}

	/**
	 * 表示終了日時(visibleEndAt)を設定する。
	 * 
	 * @param visibleEndAt 表示終了日時(visibleEndAt)
	 */
	public void setVisibleEndAt(String visibleEndAt) {
		this.visibleEndAt = visibleEndAt;
	}

	/**
	 * 有効開始日時(usableStartAt)を取得する。
	 * 
	 * @return 有効開始日時(usableStartAt)
	 */
	public String getUsableStartAt() {
		return usableStartAt;
	}

	/**
	 * 有効開始日時(usableStartAt)を設定する。
	 * 
	 * @param usableStartAt 有効開始日時(usableStartAt)
	 */
	public void setUsableStartAt(String usableStartAt) {
		this.usableStartAt = usableStartAt;
	}

	/**
	 * 有効終了日時(usableEndAt)を取得する。
	 * 
	 * @return 有効終了日時(usableEndAt)
	 */
	public String getUsableEndAt() {
		return usableEndAt;
	}

	/**
	 * 有効終了日時(usableEndAt)を設定する。
	 * 
	 * @param usableEndAt 有効終了日時(usableEndAt)
	 */
	public void setUsableEndAt(String usableEndAt) {
		this.usableEndAt = usableEndAt;
	}

	/**
	 * 限定配布後有効日数(usableDays)を取得する。
	 * 
	 * @return 限定配布後有効日数(usableDays)
	 */
	public String getUsableDays() {
		return usableDays;
	}

	/**
	 * 限定配布後有効日数(usableDays)を設定する。
	 * 
	 * @param usableDays 限定配布後有効日数(usableDays)
	 */
	public void setUsableDays(String usableDays) {
		this.usableDays = usableDays;
	}

	/**
	 * 公開ステータス(isOpen)を取得する。
	 * 
	 * @return 公開ステータス(isOpen)
	 */
	public String getIsOpen() {
		return isOpen;
	}

	/**
	 * 公開ステータス(isOpen)を設定する。
	 * 
	 * @param isOpen 公開ステータス(isOpen)
	 */
	public void setIsOpen(String isOpen) {
		this.isOpen = isOpen;
	}

	/**
	 * 任意追加項目(additionalItems)を取得する。
	 * 
	 * @return 任意追加項目(additionalItems)
	 */
	public CouponUpdateInputDTOAdditionalItems getAdditionalItems() {
		return additionalItems;
	}

	/**
	 * 任意追加項目(additionalItems)を設定する。
	 * 
	 * @param additionalItems 任意追加項目(additionalItems)
	 */
	public void setAdditionalItems(CouponUpdateInputDTOAdditionalItems additionalItems) {
		this.additionalItems = additionalItems;
	}

}
