/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * アプリ内Msg登録API(CreateAppMst).TriggerのInput DTOクラス。
 */
public class CreateAppMstInputDTOTrigger extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** 機動トリガーイベント名(eventName) */
	@JsonProperty("event_name")
	private String[] eventName;

	/** 配布期間(Period) */
	@JsonProperty("period")
	private List<CreateAppMstInputDTOPeriod> period;

	/**
	 * 機動トリガーイベント名(eventName)を取得する。
	 * 
	 * @return 機動トリガーイベント名(eventName)
	 */
	public String[] getEventName() {
		return eventName;
	}

	/**
	 * 機動トリガーイベント名(eventName)を設定する。
	 * 
	 * @param eventName 機動トリガーイベント名(eventName)
	 */
	public void setEventName(String[] eventName) {
		this.eventName = eventName;
	}

	/**
	 * 配布期間(period)を取得する。
	 * 
	 * @return 配布期間(period)
	 */
	public List<CreateAppMstInputDTOPeriod> getPeriod() {
		return period;
	}

	/**
	 * 配布期間(period)を設定する。
	 * 
	 * @param period 配布期間(period)
	 */
	public void setPeriod(List<CreateAppMstInputDTOPeriod> period) {
		this.period = period;
	}

}
