/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * アプリ内Msg登録API(CreateAppMst).MessageのInput DTOクラス。
 *
 */
public class CreateAppMstInputDTOMessage extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** テンプレートID(templateId) */
	@JsonProperty("template_id")
	private Integer templateId;

	/** タイトル(title) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("title")
	private String title;

	/** 本文(body) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("body")
	private String body;

	/** 画像URL(imageUrl) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("image_url")
	private String imageUrl;

	/** ボタン配列(Buttons) */
	@JsonProperty("buttons")
	private List<CreateAppMstInputDTOButtons> buttons;

	/**
	 * テンプレートID(templateId)を取得する。
	 * 
	 * @return テンプレートID(templateId)
	 */
	public Integer getTemplateId() {
		return templateId;
	}

	/**
	 * テンプレートID(templateId)を設定する。
	 * 
	 * @param テンプレートID(templateId)
	 */
	public void setTemplateId(Integer templateId) {
		this.templateId = templateId;
	}

	/**
	 * タイトル(title)を取得する。
	 * 
	 * @return タイトル(title)
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * タイトル(title)を設定する。
	 * 
	 * @param title タイトル(title)
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * 本文(body)を取得する。
	 * 
	 * @return 本文(body)
	 */
	public String getBody() {
		return body;
	}

	/**
	 * 本文(body)を設定する。
	 * 
	 * @param body 本文(body)
	 */
	public void setBody(String body) {
		this.body = body;
	}

	/**
	 * 画像URL(imageUrl)を取得する。
	 * 
	 * @return 画像URL(imageUrl)
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * 画像URL(imageUrl)を設定する。
	 * 
	 * @param imageUrl 画像URL(imageUrl)
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * ボタン配列(buttons)を取得する。
	 * 
	 * @return ボタン配列(buttons)
	 */
	public List<CreateAppMstInputDTOButtons> getButtons() {
		return buttons;
	}

	/**
	 * ボタン配列(buttons)を設定する。
	 * 
	 * @param buttons ボタン配列(buttons)
	 */
	public void setButtons(List<CreateAppMstInputDTOButtons> buttons) {
		this.buttons = buttons;
	}
}