/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * アプリ内Msg登録API(CreateAppMst).PeriodのInput DTOクラス。
 */
public class CreateAppMstInputDTOPeriod extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** 開始日時(start) */
	@JsonProperty("start")
	private String start;

	/** 終了日時(end) */
	@JsonProperty("end")
	private String end;

	/**
	 * 開始日時(start)を取得する。
	 * 
	 * @return 開始日時(start)
	 */
	public String getStart() {
		return start;
	}

	/**
	 * 開始日時(start)を設定する。
	 * 
	 * @param start 開始日時(start)
	 */
	public void setStart(String start) {
		this.start = start;
	}

	/**
	 * 終了日時(end)を取得する。
	 * 
	 * @return 終了日時(end)
	 */
	public String getEnd() {
		return end;
	}

	/**
	 * 終了日時(end)を設定する。
	 * 
	 * @param end 終了日時(end)
	 */
	public void setEnd(String end) {
		this.end = end;
	}
}
