/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * アプリ内Msg登録API(CreateAppMst).TargetのInput DTOクラス。
 */
public class CreateAppMstInputDTOTarget extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** セグメントID(segmentationId) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("segmentation_id")
	private Long segmentationId;

	/**
	 * セグメントID(segmentationId)を取得する。
	 * 
	 * @return セグメントID(segmentationId)
	 */
	public Long getSegmentationId() {
		return segmentationId;
	}

	/**
	 * セグメントID(segmentationId)を設定する。
	 * 
	 * @param segmentationId セグメントID(segmentationId)
	 */
	public void setSegmentationId(Long segmentationId) {
		this.segmentationId = segmentationId;
	}
}
