/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * 配信一覧取得 API(DeliveryListGet).PopupItemsのOutput DTOクラス。
 */
@JsonIgnoreProperties(ignoreUnknown=true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DeliveryListGetOutputDTOPopupItems extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** body(Body) */
	@JsonProperty("body")
	private String body;
	
	/** title(Title) */
	@JsonProperty("title")
	private String title;

	/**
	 * body(body)を取得する。
	 * 
	 * @return body(body)
	 */
	public String getBody() {
		return body;
	}

	/**
	 * body(body)を設定する。
	 * 
	 * @param body body(body)
	 */
	public void setBody(String body) {
		this.body = body;
	}
	
	/**
	 * title(title)を取得する。
	 * 
	 * @return title(title)
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * title(title)を設定する。
	 * 
	 * @param title title(title)
	 */
	public void setTitle(String title) {
		this.title = title;
	}
}
