/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 配信一覧取得 API(DeliveryListGet)のOutput DTOクラス。
 */
@JsonIgnoreProperties(ignoreUnknown=true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DeliveryListGetOutputDTO extends MapiOutputDTOBase  {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** status(Status) */
	@JsonProperty("status")
	private String status;

	/** page(Page) */
	@JsonProperty("page")
	private String page;

	/** has_next_page(HasNextPage) */
	@JsonProperty("has_next_page")
	private boolean hasNextPage;

	/** total_results(TotalResults) */
	@JsonProperty("total_results")
	private Integer totalResults;

	/**
	 * status(status)を取得する。
	 * 
	 * @return status(status)
	 */
	@XmlElement(name = "status")
	public String getStatus() {
		return status;
	}

	/**
	 * status(status)を設定する。
	 * 
	 * @param status status(status)
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/** pages(Pages) */
	@JsonProperty("pages")
	private Integer pages;

	/** result(Result) */
	@JsonProperty("result")
	private List<DeliveryListGetOutputDTOResult> result;

	/**
	 * page(page)を取得する。
	 * 
	 * @return page(page)
	 */
	public String getPage() {
		return page;
	}

	/**
	 * page(page)を設定する。
	 * 
	 * @param page page(page)
	 */
	public void setPage(String page) {
		this.page = page;
	}

	/**
	 * has_next_page(has_next_page)を取得する。
	 * 
	 * @return has_next_page(has_next_page)
	 */
	public boolean getHasNextPage() {
		return hasNextPage;
	}

	/**
	 * has_next_page(has_next_page)を設定する。
	 * 
	 * @param hasNext has_next_page(has_next_page)
	 */
	public void setHasNextPage(boolean hasNextPage) {
		this.hasNextPage = hasNextPage;
	}

	/**
	 * total_results(total_results)を取得する。
	 * 
	 * @return total_results(total_results)
	 */
	public Integer getTotalResults() {
		return totalResults;
	}

	/**
	 * total_results(total_results)を設定する。
	 * 
	 * @param totalResults total_results(total_results)
	 */
	public void setTotalResults(Integer totalResults) {
		this.totalResults = totalResults;
	}

	/**
	 * pages(pages)を取得する。
	 * 
	 * @return pages(pages)
	 */
	public Integer getPages() {
		return pages;
	}

	/**
	 * pages(pages)を設定する。
	 * 
	 * @param pages pages(pages)
	 */
	public void setPages(Integer pages) {
		this.pages = pages;
	}

	/**
	 * result(result)を取得する。
	 * 
	 * @return result(result)
	 */
	public List<DeliveryListGetOutputDTOResult> getResult() {
		return result;
	}

	/**
	 * result(result)を設定する。
	 * 
	 * @param result result(result)
	 */
	public void setResult(List<DeliveryListGetOutputDTOResult> result) {
		this.result = result;
	}
}
