/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * イベントクーポン（アプリ導入）作成テストAPI(EventCouponAppIntroTestCreate).AdditionalItemsのInput
 * DTOクラス。
 *
 */
public class EventCouponAppIntroTestCreateInputDTOAdditionalItems extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** クーポン画像(image) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("image")
	private String image;

	/** サムネイル(thumbnail) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("thumbnail")
	private String thumbnail;

	/** クーポンコード(couponCode) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("couponCode")
	private String couponCode;

	/** クーポンコードリスト(couponCodeList) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("couponCodeList")
	private List<String> couponCodeList;

	/** クーポンコード表示設定(couponCodeVisible) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("couponCodeVisible")
	private String couponCodeVisible;

	/** 加盟店ID(_merchantId) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_merchantId")
	private String _merchantId;

	/** 加盟店名(_merchantName) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_merchantName")
	private String _merchantName;

	/** 画像見出し(_imageHeading) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_imageHeading")
	private String _imageHeading;

	/** 画像(_image) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_image")
	private String _image;

	/** バーコード(_barcode) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_barcode")
	private String _barcode;

	/** バーコード区分(_barcodeType) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_barcodeType")
	private String _barcodeType;

	/** カテゴリ(_category) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_category")
	private String _category;

	/** クーポン利用単位(_useCountType) */
	@JsonProperty("_useCountType")
	private String _useCountType;

	/** 背景色(_backColor) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_backColor")
	private String _backColor;

	/** クーポン利用方法区分(_couponUseType) */
	@JsonProperty("_couponUseType")
	private String _couponUseType;

	/** プロモーションコード用リンクテキスト見出し(_promoLinkUrlHeading) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_promoLinkUrlHeading")
	private String _promoLinkUrlHeading;

	/** プロモーションコード用リンクURL(_promoLinkUrl) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_promoLinkUrl")
	private String _promoLinkUrl;

	/** インセンティブテキスト(_incentive_text) */
	@JsonProperty("_incentive_text")
	private String _incentive_text;

	/** インセンティブ単位(_incentive_unit) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_incentive_unit")
	private String _incentive_unit;

	/** インセンティブ(_incentive) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_incentive")
	private List<EventCouponAppIntroTestCreateInputDTOIncentive> _incentive;

	/** テキスト(_texts) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_texts")
	private String _texts;

	/** リンクURL(_linkUrls) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_linkUrls")
	private String _linkUrls;

	/**
	 * クーポン画像(image)を取得する。
	 * 
	 * @return クーポン画像(image)
	 */
	public String getImage() {
		return image;
	}

	/**
	 * クーポン画像(image)を設定する。
	 * 
	 * @param image クーポン画像(image)
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * サムネイル(thumbnail)を取得する。
	 * 
	 * @return サムネイル(thumbnail)
	 */
	public String getThumbnail() {
		return thumbnail;
	}

	/**
	 * サムネイル(thumbnail)を設定する。
	 * 
	 * @param thumbnail サムネイル(thumbnail)
	 */
	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	/**
	 * クーポンコード(couponCode)を取得する。
	 * 
	 * @return クーポンコード(couponCode)
	 */
	public String getCouponCode() {
		return couponCode;
	}

	/**
	 * クーポンコード(couponCode)を設定する。
	 * 
	 * @param couponCode クーポンコード(couponCode)
	 */
	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	/**
	 * クーポンコードリスト(couponCodeList)を取得する。
	 * 
	 * @return クーポンコードリスト(couponCodeList)
	 */
	public List<String> getCouponCodeList() {
		return couponCodeList;
	}

	/**
	 * クーポンコードリスト(couponCodeList)を設定する。
	 * 
	 * @param couponCodeList クーポンコードリスト(couponCodeList)
	 */
	public void setCouponCodeList(List<String> couponCodeList) {
		this.couponCodeList = couponCodeList;
	}

	/**
	 * クーポンコード表示設定(couponCodeVisible)を取得する。
	 * 
	 * @return クーポンコード表示設定(couponCodeVisible)
	 */
	public String getCouponCodeVisible() {
		return couponCodeVisible;
	}

	/**
	 * クーポンコード表示設定(couponCodeVisible)を設定する。
	 * 
	 * @param couponCodeVisible クーポンコード表示設定(couponCodeVisible)
	 */
	public void setCouponCodeVisible(String couponCodeVisible) {
		this.couponCodeVisible = couponCodeVisible;
	}

	/**
	 * 加盟店ID(_merchantId)を取得する。
	 * 
	 * @return 加盟店ID(_merchantId)
	 */
	public String get_merchantId() {
		return _merchantId;
	}

	/**
	 * 加盟店ID(_merchantId)を設定する。
	 * 
	 * @param _merchantId 加盟店ID(_merchantId)
	 */
	public void set_merchantId(String _merchantId) {
		this._merchantId = _merchantId;
	}

	/**
	 * 加盟店名(_merchantName)を取得する。
	 * 
	 * @return 加盟店名(_merchantName)
	 */
	public String get_merchantName() {
		return _merchantName;
	}

	/**
	 * 加盟店名(_merchantName)を設定する。
	 * 
	 * @param _merchantName 加盟店名(_merchantName)
	 */
	public void set_merchantName(String _merchantName) {
		this._merchantName = _merchantName;
	}

	/**
	 * 画像見出し(_imageHeading)を取得する。
	 * 
	 * @return 画像見出し(_imageHeading)
	 */
	public String get_imageHeading() {
		return _imageHeading;
	}

	/**
	 * 画像見出し(_imageHeading)を設定する。
	 * 
	 * @param _imageHeading 画像見出し(_imageHeading)
	 */
	public void set_imageHeading(String _imageHeading) {
		this._imageHeading = _imageHeading;
	}

	/**
	 * 画像(_image)を取得する。
	 * 
	 * @return 画像(_image)
	 */
	public String get_image() {
		return _image;
	}

	/**
	 * 画像(_image)を設定する。
	 * 
	 * @param _image 画像(_image)
	 */
	public void set_image(String _image) {
		this._image = _image;
	}

	/**
	 * バーコード(_barcode)を取得する。
	 * 
	 * @return バーコード(_barcode)
	 */
	public String get_barcode() {
		return _barcode;
	}

	/**
	 * バーコード(_barcode)を設定する。
	 * 
	 * @param _barcode バーコード(_barcode)
	 */
	public void set_barcode(String _barcode) {
		this._barcode = _barcode;
	}

	/**
	 * バーコード区分(_barcodeType)を取得する。
	 * 
	 * @return バーコード区分(_barcodeType)
	 */
	public String get_barcodeType() {
		return _barcodeType;
	}

	/**
	 * バーコード区分(_barcodeType)を設定する。
	 * 
	 * @param _barcodeType バーコード区分(_barcodeType)
	 */
	public void set_barcodeType(String _barcodeType) {
		this._barcodeType = _barcodeType;
	}

	/**
	 * カテゴリ(_category)を取得する。
	 * 
	 * @return カテゴリ(_category)
	 */
	public String get_category() {
		return _category;
	}

	/**
	 * カテゴリ(_category)を設定する。
	 * 
	 * @param _category カテゴリ(_category)
	 */
	public void set_category(String _category) {
		this._category = _category;
	}

	/**
	 * クーポン利用単位(_useCountType)を取得する。
	 * 
	 * @return クーポン利用単位(_useCountType)
	 */
	public String get_useCountType() {
		return _useCountType;
	}

	/**
	 * クーポン利用単位(_useCountType)を設定する。
	 * 
	 * @param _useCountType クーポン利用単位(_useCountType)
	 */
	public void set_useCountType(String _useCountType) {
		this._useCountType = _useCountType;
	}

	/**
	 * 背景色(_backColor)を取得する。
	 * 
	 * @return 背景色(_backColor)
	 */
	public String get_backColor() {
		return _backColor;
	}

	/**
	 * 背景色(_backColor)を設定する。
	 * 
	 * @param _backColor 背景色(_backColor)
	 */
	public void set_backColor(String _backColor) {
		this._backColor = _backColor;
	}

	/**
	 * クーポン利用方法区分(_couponUseType)を取得する。
	 * 
	 * @return クーポン利用方法区分(_couponUseType)
	 */
	public String get_couponUseType() {
		return _couponUseType;
	}

	/**
	 * クーポン利用方法区分(_couponUseType)を設定する。
	 * 
	 * @param _couponUseType クーポン利用方法区分(_couponUseType)
	 */
	public void set_couponUseType(String _couponUseType) {
		this._couponUseType = _couponUseType;
	}

	/**
	 * プロモーションコード用リンクテキスト見出し(_promoLinkUrlHeading)を取得する。
	 * 
	 * @return プロモーションコード用リンクテキスト見出し(_promoLinkUrlHeading)
	 */
	public String get_promoLinkUrlHeading() {
		return _promoLinkUrlHeading;
	}

	/**
	 * プロモーションコード用リンクテキスト見出し(_promoLinkUrlHeading)を設定する。
	 * 
	 * @param _promoLinkUrlHeading プロモーションコード用リンクテキスト見出し(_promoLinkUrlHeading)
	 */
	public void set_promoLinkUrlHeading(String _promoLinkUrlHeading) {
		this._promoLinkUrlHeading = _promoLinkUrlHeading;
	}

	/**
	 * プロモーションコード用リンクURL(_promoLinkUrl)を取得する。
	 * 
	 * @return プロモーションコード用リンクURL(_promoLinkUrl)
	 */
	public String get_promoLinkUrl() {
		return _promoLinkUrl;
	}

	/**
	 * プロモーションコード用リンクURL(_promoLinkUrl)を設定する。
	 * 
	 * @param _promoLinkUrl プロモーションコード用リンクURL(_promoLinkUrl)
	 */
	public void set_promoLinkUrl(String _promoLinkUrl) {
		this._promoLinkUrl = _promoLinkUrl;
	}

	/**
	 * インセンティブテキスト(_incentive_text)を取得する。
	 * 
	 * @return インセンティブテキスト(_incentive_text)
	 */
	public String get_incentive_text() {
		return _incentive_text;
	}

	/**
	 * インセンティブテキスト(_incentive_text)を設定する。
	 * 
	 * @param _incentive_text インセンティブテキスト(_incentive_text)
	 */
	public void set_incentive_text(String _incentive_text) {
		this._incentive_text = _incentive_text;
	}

	/**
	 * インセンティブ単位(_incentive_unit)を取得する。
	 * 
	 * @return インセンティブ単位(_incentive_unit)
	 */
	public String get_incentive_unit() {
		return _incentive_unit;
	}

	/**
	 * インセンティブ単位(_incentive_unit)を設定する。
	 * 
	 * @param _incentive_unit インセンティブ単位(_incentive_unit)
	 */
	public void set_incentive_unit(String _incentive_unit) {
		this._incentive_unit = _incentive_unit;
	}

	/**
	 * インセンティブ(_incentive)を取得する。
	 * 
	 * @return インセンティブ(_incentive)
	 */
	public List<EventCouponAppIntroTestCreateInputDTOIncentive> get_incentive() {
		return _incentive;
	}

	/**
	 * インセンティブ(_incentive)を設定する。
	 * 
	 * @param _incentive インセンティブ(_incentive)
	 */
	public void set_incentive(List<EventCouponAppIntroTestCreateInputDTOIncentive> _incentive) {
		this._incentive = _incentive;
	}

	/**
	 * テキスト(_texts)を取得する。
	 * 
	 * @return テキスト(_texts)
	 */
	public String get_texts() {
		return _texts;
	}

	/**
	 * テキスト(_texts)を設定する。
	 * 
	 * @param _texts テキスト(_texts)
	 */
	public void set_texts(String _texts) {
		this._texts = _texts;
	}

	/**
	 * リンクURL(_linkUrls)を取得する。
	 * 
	 * @return リンクURL(_linkUrls)
	 */
	public String get_linkUrls() {
		return _linkUrls;
	}

	/**
	 * リンクURL(_linkUrls)を設定する。
	 * 
	 * @param _linkUrls リンクURL(_linkUrls)
	 */
	public void set_linkUrls(String _linkUrls) {
		this._linkUrls = _linkUrls;
	}
}