/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * イベントクーポン（アプリ導入）作成テストAPI(EventCouponAppIntroTestCreate)のOutput DTOクラス。
 */
@JsonIgnoreProperties(ignoreUnknown=true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class EventCouponAppIntroTestCreateOutputDTO extends MapiOutputDTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** 実行結果(Status) */
	@JsonProperty("status")
	private String status;

	/** 現在タイムスタンプ(Timestamp) */
	@JsonProperty("timestamp")
	private String timestamp;

	/** クーポンUUID(uuid) */
	@JsonProperty("uuid")
	private String uuid;

	/** 配信ID(DeliveryId) */
	@JsonProperty("deliveryId")
	private Long deliveryId;

	/**
	 * 実行結果(status)を取得する。
	 * 
	 * @return 実行結果(status)
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * 実行結果(status)を設定する。
	 * 
	 * @param status 実行結果(status)
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * 現在タイムスタンプ(timestamp)を取得する。
	 * 
	 * @return 現在タイムスタンプ(timestamp)
	 */
	public String getTimestamp() {
		return timestamp;
	}

	/**
	 * 現在タイムスタンプ(timestamp)を設定する。
	 * 
	 * @param timestamp 現在タイムスタンプ(timestamp)
	 */
	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * クーポンUUID(uuid)を取得する。
	 * 
	 * @return クーポンUUID(uuid)
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * クーポンUUID(uuid)を設定する。
	 * 
	 * @param uuid クーポンUUID(uuid)
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * 配信ID(deliveryId)を取得する。
	 * 
	 * @return 配信ID(deliveryId)
	 */
	public Long getDeliveryId() {
		return deliveryId;
	}

	/**
	 * 配信ID(deliveryId)を設定する。
	 * 
	 * @param deliveryId 配信ID(deliveryId)
	 */
	public void setDeliveryId(Long deliveryId) {
		this.deliveryId = deliveryId;
	}

}
