/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;
import com.ibm.jp.awag.common.validator.Required;

/**
 * イベントクーポン（アプリ導入）作成テストAPI(EventCouponAppIntroTestCreate)._incentiveのInput DTOクラス。
 */
public class EventCouponAppIntroTestCreateInputDTOIncentive extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** インセンティブ表示順 */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_priority")
	private String _priority;

	/** クーポン本文テキスト(_couponText) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_couponText")
	private String _couponText;

	/** 割引率(_amount) */
	@Required
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_amount")
	private String _amount;

	/** 割引単位(_unit) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_unit")
	private String _unit;

	/** 対象商品(_products) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("_products")
	private String _products;

	/**
	 * インセンティブ表示順(_priority)を取得する。
	 * 
	 * @return インセンティブ表示順(_priority)
	 */
	public String get_priority() {
		return _priority;
	}

	/**
	 * インセンティブ表示順(_priority)を設定する。
	 * 
	 * @param _priority インセンティブ表示順(_priority)
	 */
	public void set_priority(String _priority) {
		this._priority = _priority;
	}

	/**
	 * クーポン本文テキスト(_couponText)を取得する。
	 * 
	 * @return クーポン本文テキスト(_couponText)
	 */
	public String get_couponText() {
		return _couponText;
	}

	/**
	 * クーポン本文テキスト(_couponText)を設定する。
	 * 
	 * @param _couponText クーポン本文テキスト(_couponText)
	 */
	public void set_couponText(String _couponText) {
		this._couponText = _couponText;
	}

	/**
	 * 割引率(_amount)を取得する。
	 * 
	 * @return 割引率(_amount)
	 */
	public String get_amount() {
		return _amount;
	}

	/**
	 * 割引率(_amount)を設定する。
	 * 
	 * @param _amount 割引率(_amount)
	 */
	public void set_amount(String _amount) {
		this._amount = _amount;
	}

	/**
	 * 割引単位(_unit)を取得する。
	 * 
	 * @return 割引単位(_unit)
	 */
	public String get_unit() {
		return _unit;
	}

	/**
	 * 割引単位(_unit)を設定する。
	 * 
	 * @param _unit 割引単位(_unit)
	 */
	public void set_unit(String _unit) {
		this._unit = _unit;
	}

	/**
	 * 対象商品(_products)を取得する。
	 * 
	 * @return 対象商品(_products)
	 */
	public String get_products() {
		return _products;
	}

	/**
	 * 対象商品(_products)を設定する。
	 * 
	 * @param _products 対象商品(_products)
	 */
	public void set_products(String _products) {
		this._products = _products;
	}
}
