/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * イベントクーポン（アプリ導入）作成テストAPI(EventCouponAppIntroTestCreate).ConditionのInput DTOクラス。
 */
public class EventCouponAppIntroTestCreateInputDTOCondition extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** カテゴリ(category) */
	@JsonInclude(JsonInclude.Include.NON_NULL)
	@JsonProperty("category")
	private String category;

	/**
	 * カテゴリ(category)を取得する。
	 * 
	 * @return カテゴリ(category)
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * カテゴリ(category)を設定する。
	 * 
	 * @param category カテゴリ(category)
	 */
	public void setCategory(String category) {
		this.category = category;
	}
}
