/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * FANSHIP inAppMSG（配信停止）API(FanshipInAppMsgUnsubscribe)のOutput DTOクラス。
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FanshipInAppMsgUnsubscribeOutputDTO extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** エラー詳細配列(Detail) */
	@JsonProperty("detail")
	private List<FanshipInAppMsgUnsubscribeOutputDTODetail> detail;

	/**
	 * エラー詳細配列(detail)を取得する。
	 * 
	 * @return エラー詳細配列(detail)
	 */
	public List<FanshipInAppMsgUnsubscribeOutputDTODetail> getDetail() {
		return detail;
	}

	/**
	 * エラー詳細配列(detail)を設定する。
	 * 
	 * @param detail エラー詳細配列(detail)
	 */
	public void setDetail(List<FanshipInAppMsgUnsubscribeOutputDTODetail> detail) {
		this.detail = detail;
	}
}
