/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import javax.validation.Valid;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * 登録者情報一覧取得 API(RegisterInfoListGet).FilterのInput DTOクラス。
 *
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class RegisterInfoListGetInputDTOFilter extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** popinfo_id(PopinfoId) */
	@Valid
	@JsonProperty(value = "popinfo_id")
	private String popinfoId;

	/** test_send(TestSend) */
	@Valid
	@JsonProperty(value = "test_send")
	private Boolean testSend;

	/**
	 * popinfo_id(popinfo_id)を取得する。
	 * 
	 * @return popinfo_id(popinfo_id)
	 */
	public String getPopinfoId() {
		return popinfoId;
	}

	/**
	 * popinfo_id(popinfo_id)を設定する。
	 * 
	 * @param popinfoId popinfo_id(popinfo_id)
	 */
	public void setPopinfoId(String popinfoId) {
		this.popinfoId = popinfoId;
	}

	/**
	 * test_send(test_send)を取得する。
	 * 
	 * @return test_send(test_send)
	 */
	public @Valid Boolean getTestSend() {
		return testSend;
	}

	/**
	 * test_send(test_send)を設定する。
	 * 
	 * @param testSend test_send(test_send)
	 */
	public void setTestSend(Boolean testSend) {
		this.testSend = testSend;
	}
}