/** Generated by AWAG */

package jp.co.aeoncredit.coupon.batch.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.ibm.jp.awag.common.dto.DTOBase;

/**
 * 登録者情報一覧取得 API(RegisterInfoListGet).TestSendのInput DTOクラス。
 *
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class RegisterInfoListGetInputDTOTestSend extends DTOBase {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	/** $gte($gte) */
	// @DisplayName(key = "RegisterInfoListGetInput.$gte")
	private String $gte;

	/** $gt($gt) */
	// @DisplayName(key = "RegisterInfoListGetInput.$gt")
	private String $gt;

	/** $lt($lt) */
	// @DisplayName(key = "RegisterInfoListGetInput.$lt")
	private String $lt;

	/** $lte($lte) */
	// @DisplayName(key = "RegisterInfoListGetInput.$lte")
	private String $lte;

	/** $in($in) */
	// @DisplayName(key = "RegisterInfoListGetInput.$in")
	private String $in;

	/** $or($or) */
	// @DisplayName(key = "RegisterInfoListGetInput.$or")
	private String $or;

	/** $and($and) */
	// @DisplayName(key = "RegisterInfoListGetInput.$and")
	private String $and;

	/**
	 * $gte($gte)を取得する。
	 * 
	 * @return $gte($gte)
	 */
	public String get$gte() {
		return $gte;
	}

	/**
	 * $gte($gte)を設定する。
	 * 
	 * @param $gte $gte($gte)
	 */
	public void set$gte(String $gte) {
		this.$gte = $gte;
	}

	/**
	 * $gt($gt)を取得する。
	 * 
	 * @return $gt($gt)
	 */
	public String get$gt() {
		return $gt;
	}

	/**
	 * $gt($gt)を設定する。
	 * 
	 * @param $gt $gt($gt)
	 */
	public void set$gt(String $gt) {
		this.$gt = $gt;
	}

	/**
	 * $lt($lt)を取得する。
	 * 
	 * @return $lt($lt)
	 */
	public String get$lt() {
		return $lt;
	}

	/**
	 * $lt($lt)を設定する。
	 * 
	 * @param $lt $lt($lt)
	 */
	public void set$lt(String $lt) {
		this.$lt = $lt;
	}

	/**
	 * $lte($lte)を取得する。
	 * 
	 * @return $lte($lte)
	 */
	public String get$lte() {
		return $lte;
	}

	/**
	 * $lte($lte)を設定する。
	 * 
	 * @param $lte $lte($lte)
	 */
	public void set$lte(String $lte) {
		this.$lte = $lte;
	}

	/**
	 * $in($in)を取得する。
	 * 
	 * @return $in($in)
	 */
	public String get$in() {
		return $in;
	}

	/**
	 * $in($in)を設定する。
	 * 
	 * @param $in $in($in)
	 */
	public void set$in(String $in) {
		this.$in = $in;
	}

	/**
	 * $or($or)を取得する。
	 * 
	 * @return $or($or)
	 */
	public String get$or() {
		return $or;
	}

	/**
	 * $or($or)を設定する。
	 * 
	 * @param $or $or($or)
	 */
	public void set$or(String $or) {
		this.$or = $or;
	}

	/**
	 * $and($and)を取得する。
	 * 
	 * @return $and($and)
	 */
	public String get$and() {
		return $and;
	}

	/**
	 * $and($and)を設定する。
	 * 
	 * @param $and $and($and)
	 */
	public void set$and(String $and) {
		this.$and = $and;
	}
}